name: Deploy to Heroku GANDU

on: 
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: 5hojib/heroku-deploy-action@v2
        with:
          heroku_api_key: 'HRKU-cb5ac525-c15e-4327-8b8b-9f5807ed9b6d'
          heroku_app_name: 'noice42'
          heroku_email: 'a1.streamflix@outlook.com'
          team: 'streamflix-team2'
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
